---
- hosts: webservers
  become: yes
  become_method: sudo
  gather_facts: False
  vars:
    worker_processes: 4
    num_cpus: 2
    max_open_file: 65505
  tasks:
    - name: ensurce nginx is the latest version
      yum: name=nginx state=latest
    - name: write the nginx config file
      template: src=../playbook/nginx/roles/web/templates/nginx2.conf dest=/etc/nginx/nginx.conf validate='nginx -t -c %s'
      notify:
        - restart nginx
    - name: ensure nginx is running
      service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
